plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/rhys/Desktop/FloQast quiz - claude"
publishOrigin = "config"
commandOrigin = "ui"
base = "/Users/rhys/Desktop/FloQast quiz - claude"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "ALLOWALL"
Content-Security-Policy = "frame-ancestors *"